'use client'

import { useEffect, useState } from 'react'
import Header from '@/components/Header'
import ProgressBar from '@/components/ProgressBar'
import HeroBanner from '@/components/HeroBanner'
import SocialProof from '@/components/SocialProof'
import Services from '@/components/Services'
import BeforeAfter from '@/components/BeforeAfter'
import About from '@/components/About'
import Portfolio from '@/components/Portfolio'
import Stats from '@/components/Stats'
import Process from '@/components/Process'
import Technologies from '@/components/Technologies'
import Timeline from '@/components/Timeline'
import Testimonials from '@/components/Testimonials'
import Pricing from '@/components/Pricing'
import FAQ from '@/components/FAQ'
import Guarantee from '@/components/Guarantee'
import Urgency from '@/components/Urgency'
import CTA from '@/components/CTA'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import WhatsAppButton from '@/components/WhatsAppButton'